name: Test1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
      with:
        swift-version: "5.3.3"
    - name: Get swift version 
      run: swift --version
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
